name: Update JSON

on:
  push:
    paths:
      - input.txt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Read input and update data.json
      run: |
        INPUT=$(cat input.txt)
        echo "{ \"message\": \"$INPUT\" }" > data.json

    - name: Commit changes
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/AntSur1/json-test-update.git
        git add data.json
        git commit -m "Update data.json from input.txt"
        git push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

